server:
  port: 8081

spring:
  application:
    name: advertising_exposure
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/advertising_platform
    username: root
    password: 1234
  rabbitmq:
    host: localhost
    port: 5672

  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        format_sql: true
        show_sql: true
  elasticsearch:
    uris: http://localhost:9200
  data:
    elasticsearch:
      repositories:
        enabled: true
  batch:
    job:
      enabled: false
    jdbc:
      initialize-schema: always

es:
  host: localhost
  port: 9200